version: '3.8'
services:
  postgres:
    image: bitnami/postgresql
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: calendarapp
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
